### ISSUE TITLE
Person without details should still render

### ISSUE THREAD

**Issue by kwannoel** [Holmusk/HolmuskDB#131]
To reproduce:
1. Create a resource
2. Search for the resource via a `term`
3. Click on the person in the results
4. Delete all terms associated to the person
5. Refresh
  Here we should render the person's name. What actually happens is everything is not rendered.

**Comment by dzhou343** [comment]
This issue stems from the query require there to be a person, a relation and a term. A possible solution would be to check whether the return of a query is empty, and if it is, then we can reperform the query with a different function is search solely for the person.
