### ISSUE TITLE
Propagate errors in handlers to middleware

### ISSUE THREAD

**Issue by leyliramazanova** [Holmusk/HolmuskDB#46]
Eventually we should propagate our errors into a middleware
https://expressjs.com/en/guide/error-handling.html

**Comment by kwannoel** [comment]
Resolved in https://github.com/Holmusk/HolmuskDB/commit/073f530addfb78778ab5ced8e4008aa2d745ec16#diff-c80ebcb71220d7e50dd00f199b9d4d2a
