### ISSUE TITLE
Ability to run a specific unit test

### ISSUE THREAD

**Issue by leyliramazanova** [Holmusk/HolmuskDB#77]
As opposed to having to run all unit tests every time we want to test, we should be able to choose which unit test to run.

**Comment by dzhou343** [comment]
I believe this answers this issue

https://stackoverflow.com/questions/42827054/how-do-i-run-a-single-test-using-jest

**Comment by kwannoel** [comment]
https://github.com/Holmusk/HolmuskDB/tree/master/backend#testing addressed in README
