### ISSUE TITLE
Consolidating server-handlers and db-queries

### ISSUE THREAD

**Issue by leyliramazanova** [Holmusk/HolmuskDB#79]
- `conversion functions` are called within `db-queries`
- `processing functions` are called in `server-handlers`.
- `db-queries` are then imported in `server-handlers`. 

As you can see, the functionality is convoluted.
Hence we encounter hard to debug errors when using these files.

A possible implementation is to process parameters before running queries. E.g. in db-queries.js, we apply process.addResource on parameters before converting the paramaters into a query.

**Comment by kwannoel** [comment]
Alternatively, looking at functions in db-queries.js, they are doing the very similar things and do not contain huge amounts of logic.

*Only difference between the 2 would be the conversion function*
```js
// Deletes a node and removes all outgoing or incoming nodes
async function deleteResource (driver, personResource) {
  const { params, query } = queryConvert.convertDeleteResource(personResource)
  await runQuery(driver, query, params)
  return true
}

// Deletes a label from a term
async function deleteLabel (driver, personResource) {
  const { params, query } = queryConvert.convertDeleteLabel(personResource)
  await runQuery(driver, query, params)
  return true
}
```

Hence we could remove the entire db-queries file and just put all the required functionality in the `server-handlers`.

That way we have a single source to test.

@leyliramazanova
